version: "3"

services:
  backend:
    build: ./src/backend
    restart: always
    container_name: vbank_backend
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
      target: prod-pwa-stage
    restart: always
    container_name: vbank_client
    ports:
      - "8080:80"
    depends_on:
      - backend


  db:
    image: mysql:8.0
    container_name: vbank_db
    restart: always
    #    command:
    #      - '--secure-file-priv=""'
    #      - '--local-infile=1'
    environment:
      MYSQL_DATABASE: "bank"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_USER: "root"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: vbank_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "7070:80"
    depends_on:
      - db
